### ISSUE TITLE
在yolov5.cpp中common.h没有找到

### ISSUE THREAD

**Issue by ZhangChaoZhong** [linghu8812/tensorrt_inference#1]
在vs2019生成trt模型时，报错:在yolov5.cpp中common.h没有找到

**Comment by ZhangChaoZhong** [comment]
请问谁可以帮忙解答一下，谢谢！！

**Comment by linghu8812** [comment]
> 在vs2019生成trt模型时，报错:在yolov5.cpp中common.h没有找到

你好，common.h的路径在这里，[https://github.com/linghu8812/tensorrt_inference/tree/master/includes/common](https://github.com/linghu8812/tensorrt_inference/tree/master/includes/common)，配置路径时包含一下。

**Comment by ZhangChaoZhong** [comment]
感谢，解决了。
