### ISSUE TITLE
export opset_version=12 causes an error

### ISSUE THREAD

**Issue by arnoldfychen** [linghu8812/tensorrt_inference#10]
torch.onnx.export with opset_version=12 requires onnx version 1.8, if I upgrade onnx from 1.6 to 1.8, then the following error happened while executing 'python3 models/export_onnx.py --weights ./weights/yolov4-p5.pt --img-size 896' :

Traceback (most recent call last):
  File "models/export_onnx.py", line 9, in <module>
    from onnxsim import simplify
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/__init__.py", line 1, in <module>
    from onnxsim.onnx_simplifier import simplify
  File "/usr/local/lib/python3.6/dist-packages/onnxsim/onnx_simplifier.py", line 6, in <module>
    import onnx  # type: ignore
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: /usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN6google8protobuf7MessageE

but on my ubuntu18.04, libprotobuf-dev is already the latest version.

**Comment by linghu8812** [comment]
@arnoldfychen there is no need to use onnx 1.8.0, onnx==1.6.0 is ok.

**Comment by arnoldfychen** [comment]
torch.onnx.export(model, img, f, verbose=False, opset_version=12, input_names=['images'],
                          output_names=['output'])

But opset version 12 is not supported by onnx1.6

**Comment by arnoldfychen** [comment]
Yes, after I rebuilt mish_cuda with pytorch1.6, then downgrade onnx to1.6, export can work well, thanks

**Comment by arnoldfychen** [comment]
Yes, after I rebuilt mish_cuda with pytorch1.6, then downgraded onnx to1.6, torch.onnx.export worked well with opset 12, thanks
