### ISSUE TITLE
mish_cuda cannot build with pytorch1.6

### ISSUE THREAD

**Issue by arnoldfychen** [linghu8812/tensorrt_inference#11]
ScaledYOLOv4-large depends on mish_cuda, so I build mish_cuda following these steps:

git clone https://github.com/thomasbrandon/mish-cuda mc
cd mc

change all of name which is mish_cuda to mish_mish and build.
1. mc/src/mish_cuda -> mc/src/mish_mish
2. mc/csrc/mish_cuda.cpp -> mc/csrc/mish_mish.cpp
3. in mc/setup.py
3.1 line 5 -> 'csrc/mish_mish.cpp'
3.2 line 11 -> name='mish_mish'
3.3 line 20 -> 'mish_mish._C'

python setup.py build

but the following error happened with 'python setup.py build' : 
/workspace/ScaledYOLOv4/mc/csrc/mish_kernel.cu:3:10: fatal error: CUDAApplyUtils.cuh: No such file or directory
 #include "CUDAApplyUtils.cuh"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

 I checked and found pytorch1.6 has no CUDAApplyUtils.cuh, so, I downgrade pytorch to 1.4, then 'python setup.py build' ran successfully.

But in your https://github.com/linghu8812/tensorrt_inference/blob/master/ScaledYOLOv4/requirements.txt, it requires :
   onnx ==1.6.0
   pytorch >= 1.6.0
   onnx-simplifier 

But the actual building mish_cuda and export onnx shows onnx version should be 1.8 and pytorch version should be less than 1.6,  I want to know what's the exact versions you used with these tools ?   thanks

**Comment by linghu8812** [comment]
@arnoldfychen use pytorch>=1.6.0 is ok, see https://github.com/WongKinYiu/ScaledYOLOv4/issues/27#issuecomment-730254099, or copy `CUDAApplyUtils.cuh` in `external` folder to `csrc` folder.
