### ISSUE TITLE
error: 'cudaStream_t' has not been declared

### ISSUE THREAD

**Issue by kk52099** [linghu8812/tensorrt_inference#115]
when i  run "make", 
![image](https://user-images.githubusercontent.com/18585577/140028123-e8ee9391-97ff-470e-ab41-dd76afe8b0a5.png)

**Comment by linghu8812** [comment]
it was defined in `/usr/local/cuda-10.2/targets/x86_64-linux/include/driver_types.h`

**Comment by kk52099** [comment]
@linghu8812 感谢回答， 我在这个目录上确实找到有， 但为啥cmake，却报错尼
