### ISSUE TITLE
Missing model.h

### ISSUE THREAD

**Issue by spacewalk01** [linghu8812/tensorrt_inference#138]
Hi thank you for sharing your implementation.

I am trying to run mmpose but there is a missing model.h file in mmpose.h. Where can I find it?

Thanks

**Comment by linghu8812** [comment]
https://github.com/linghu8812/tensorrt_inference/blob/master/includes/common/model.h

**Comment by linghu8812** [comment]
https://github.com/linghu8812/tensorrt_inference/blob/master/mmpose/mmpose.cpp#L10

**Comment by spacewalk01** [comment]
Thanks for your quick reply
