### ISSUE TITLE
face_alignment error

### ISSUE THREAD

**Issue by pcb9382** [linghu8812/tensorrt_inference#149]
`./face_alignment_trt ../../../configs/face_alignment/config.yaml ../../../samples/faces_recognition`
error:
 ./face_alignment_trt ../../../configs/face_alignment/config.yaml ../../../samples/faces_recognition
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; first invalid key: "resize"
已放弃 (核心已转储)

**Comment by linghu8812** [comment]
在`../../../configs/face_alignment/config.yaml`文件中添加一个key:
```
resize:        "directly"
```

**Comment by linghu8812** [comment]
solved by https://github.com/linghu8812/tensorrt_inference/commit/847a61e6429391349de9826fd52daf8888146860
