### ISSUE TITLE
/yolov4/ScaledYOLOv4.cpp:2:10: fatal error: yaml-cpp/yaml.h: No such file or directory

### ISSUE THREAD

**Issue by chandu1263** [linghu8812/tensorrt_inference#15]
Facing this issue while doing make.
How to fix this issue?

**Comment by chandu1263** [comment]
Solved this issue by installing libyaml
' apt-get install -y libyaml-cpp-dev'

**Comment by linghu8812** [comment]
there is no need, `yaml.h` has already been [here](https://github.com/linghu8812/tensorrt_inference/blob/master/includes/yaml-cpp/include/yaml-cpp/yaml.h)
