### ISSUE TITLE
Cuda Error (out of memory)

### ISSUE THREAD

**Issue by thuongnct** [linghu8812/tensorrt_inference#155]
I was deploying yolov4 tiny, but I met the error below

```----------------------------------------------------------------
[09/29/2022-16:59:38] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.

start building engine
[09/29/2022-16:59:38] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[09/29/2022-16:59:38] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
build engine done
tensorrt_inference: /home/thuong/source/tensorrt_inference/code/src/model.cpp:46: void Model::OnnxToTRTModel(): Assertion `engine' failed.
Aborted (core dumped)```

Running command is:

`./tensorrt_inference Yolov4 ../configs/Yolov4/config-tiny.yaml ../samples/detection_segmentation`

Tensorrt, cuda, onnx, and onnxsim version:

- torch: 1.12.1
- onnx: 1.12.0
- onnx: 0.3.6
- cuda: 10-2
- tensorrt: 7.1.3
```

I also check gpu operating percent by nvidia-smi. It is almost 10%

![image](https://user-images.githubusercontent.com/96158175/192976535-ce27347a-9338-43ec-8a46-1743dbdf05cb.png)

Does any body meet the same issue? Please give me some ideas for solving it.

**Comment by linghu8812** [comment]
> I was deploying yolov4 tiny, but I met the error below
> 
> ```
> [09/29/2022-16:59:38] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> 
> start building engine
> [09/29/2022-16:59:38] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
> [09/29/2022-16:59:38] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
> build engine done
> tensorrt_inference: /home/thuong/source/tensorrt_inference/code/src/model.cpp:46: void Model::OnnxToTRTModel(): Assertion `engine' failed.
> Aborted (core dumped)```
> 
> Running command is:
> 
> `./tensorrt_inference Yolov4 ../configs/Yolov4/config-tiny.yaml ../samples/detection_segmentation`
> 
> Tensorrt, cuda, onnx, and onnxsim version:
> 
> - torch: 1.12.1
> - onnx: 1.12.0
> - onnx: 0.3.6
> - cuda: 10-2
> - tensorrt: 7.1.3
> ```
> 
> I also check gpu operating percent by nvidia-smi. It is almost 10%
> 
> ![image](https://user-images.githubusercontent.com/96158175/192976535-ce27347a-9338-43ec-8a46-1743dbdf05cb.png)
> 
> Does any body meet the same issue? Please give me some ideas for solving it.

change this line to a smaller size lowwer than your GPU memory, [https://github.com/linghu8812/tensorrt_inference/blob/master/code/src/model.cpp#L40](https://github.com/linghu8812/tensorrt_inference/blob/master/code/src/model.cpp#L40)

**Comment by thuongnct** [comment]
@linghu8812 thank you so much. It worked!
