### ISSUE TITLE
no tensorrt_inference generate, 

### ISSUE THREAD

**Issue by alicera** [linghu8812/tensorrt_inference#159]
https://github.com/linghu8812/tensorrt_inference#how-to-use
no tensorrt_inference generate, 
I build success

```
 1914 |     TRT_DEPRECATED bool execute(int32_t batchSize, void* const* bindings) noexcept
      |                         ^~~~~~~
[ 95%] Building CXX object YOLOv6/CMakeFiles/YOLOv6.dir/work/AI/YOLOv7/tensorrt/tensorrt_inference/code/src/YOLO.cpp.o
[ 96%] Building CXX object YOLOv6/CMakeFiles/YOLOv6.dir/work/AI/YOLOv7/tensorrt/tensorrt_inference/code/src/YOLOv6.cpp.o
[ 97%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libyolov5.so
[ 98%] Built target yolov5
[ 98%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libYolov4.so
[ 99%] Built target Yolov4
[ 99%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libYOLOv6.so
[ 99%] Built target YOLOv6
[ 99%] Building CXX object CMakeFiles/tensorrt_inference.dir/main.cpp.o
[100%] Linking CXX executable /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/tensorrt_inference
[100%] Built target tensorrt_inference

```

```
CMakeCache.txt  FCN         RetinaFace        YOLOv6   arcface              face_alignment  ghostnet       mmpose   seresnext  yolov7
CMakeFiles      Makefile    ScaledYOLOv4      Yolov4   cmake_install.cmake  fast-reid       lenet          nanodet  yolor
CenterFace      MiniFASNet  Swin-Transformer  alexnet  efficientnet         gender-age      libfactory.so  scrfd    yolov5
```

**Comment by linghu8812** [comment]
> https://github.com/linghu8812/tensorrt_inference#how-to-use no tensorrt_inference generate, I build success
> 
> ```
>  1914 |     TRT_DEPRECATED bool execute(int32_t batchSize, void* const* bindings) noexcept
>       |                         ^~~~~~~
> [ 95%] Building CXX object YOLOv6/CMakeFiles/YOLOv6.dir/work/AI/YOLOv7/tensorrt/tensorrt_inference/code/src/YOLO.cpp.o
> [ 96%] Building CXX object YOLOv6/CMakeFiles/YOLOv6.dir/work/AI/YOLOv7/tensorrt/tensorrt_inference/code/src/YOLOv6.cpp.o
> [ 97%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libyolov5.so
> [ 98%] Built target yolov5
> [ 98%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libYolov4.so
> [ 99%] Built target Yolov4
> [ 99%] Linking CXX shared library /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/libYOLOv6.so
> [ 99%] Built target YOLOv6
> [ 99%] Building CXX object CMakeFiles/tensorrt_inference.dir/main.cpp.o
> [100%] Linking CXX executable /work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/tensorrt_inference
> [100%] Built target tensorrt_inference
> ```
> 
> ```
> CMakeCache.txt  FCN         RetinaFace        YOLOv6   arcface              face_alignment  ghostnet       mmpose   seresnext  yolov7
> CMakeFiles      Makefile    ScaledYOLOv4      Yolov4   cmake_install.cmake  fast-reid       lenet          nanodet  yolor
> CenterFace      MiniFASNet  Swin-Transformer  alexnet  efficientnet         gender-age      libfactory.so  scrfd    yolov5
> ```

it has been built in `/work/AI/YOLOv7/tensorrt/tensorrt_inference/bin/` folder
