### ISSUE TITLE
tensorrt_inference/nanodet/nanodet.cpp:59: bool nanodet::InferenceFolder(const string&): Assertion `engine->getNbBindings() == 2' failed. 已放弃 (核心已转储)

### ISSUE THREAD

**Issue by Wulingtian** [linghu8812/tensorrt_inference#17]
当我做nanodet trt推理的时候，报错；我打印了engine->getNbBindings() ，发现engine->getNbBindings() == 7而不是等于2；我检查了网络，发现网络有一个输入和6个输出；请问怎么转换成一个输入和一个输出的模型呢？

**Comment by KimYJ12** [comment]
I also encountered the same error. 
When I remove the part(assert(engine->getNbBindings() == 2)),
the following error occurs.

loading filename from:../yolov4-p7.trt
deserialize done
[12/21/2020-17:28:42] [W] [TRT] Total space of persistent layer space is 486812 on host and 2471966208 on device
binding0: 28311552
binding1: 50135040
binding2: 12533760
binding3: 3133440
binding4: 783360
binding5: 195840
Processing: ../samples//eagle.jpg
prepareImage
prepare image take: 230.207 ms.
host2device
execute
[12/21/2020-17:28:43] [E] [TRT] engine.cpp (1036) - Cuda Error in executeInternal: 700 (an illegal memory access was encountered)
[12/21/2020-17:28:43] [E] [TRT] FAILED_EXECUTION: std::exception
Inference take: 289.998 ms.
execute success
device2host
post process
Segmentation fault (core dumped)

**Comment by linghu8812** [comment]
@Wulingtian 
please use this [pro](https://github.com/linghu8812/nanodet) to export nanodet onnx

**Comment by linghu8812** [comment]
@KimYJ12 please use this [pro](https://github.com/linghu8812/ScaledYOLOv4/tree/yolov4-large) to export yolov4-p7 onnx.

**Comment by AderonHuang** [comment]
> 当我做nanodet trt推理的时候，报错；我打印了engine->getNbBindings() ，发现engine->getNbBindings() == 7而不是等于2；我检查了网络，发现网络有一个输入和6个输出；请问怎么转换成一个输入和一个输出的模型呢？

楼主请问这个问题解决了吗，我也遇到了这个问题，用的是https://github.com/linghu8812/tensorrt_inference/tree/master/ScaledYOLOv4这个里面的export_onnx.py转换的，和 @linghu8812 提供的是一样的呀
