### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Egorundel** [linghu8812/tensorrt_inference#170]
Hello, I have the following problem:

![Screenshot from 2023-07-06 12-12-10](https://github.com/linghu8812/tensorrt_inference/assets/65890558/dc1c092a-8173-4bcc-bfd8-b6906c2c328a)

Can you help me to solve this problem, please?

**TensorRT Version:** 7.2.2.3.

**NVIDIA GPU:** RTX 2070

**CUDA Version:** 11.1

**Operationg System:** Ubuntu 20.04

**Comment by Egorundel** [comment]
The problem was solved by replacing 
`void *buffers[2];` 
in model.h on 
`void *buffers[5];`

and in model.cpp changed the line 
`assert(engine->getNbBindings() == 2); `
to 
`assert(engine->getNbBindings() == 5);`

Do this if you use the NMS Plugin in the model :)

**Comment by c7-biu** [comment]
Hi! I have met this problem too! Could you please share the solutions with me? Thank you!

**Comment by Egorundel** [comment]
Attach your ONNX-model, I will try to understand your problem

**Comment by Egorundel** [comment]
@c7-biu 
Attach your ONNX-model, I will try to understand your problem

**Comment by c7-biu** [comment]
> 附上您的ONNX模型，我将尝试理解您的问题
I didn't use ONNX,I try to ues the tensorrtx  to accelerate the yolov8,but the problem i met is similar with you.

> 
![Uploading prolem.png…]()

**Comment by c7-biu** [comment]
I didn't use ONNX,I try to ues the tensorrtx to accelerate the yolov8,but the problem i met is similar with you.
![prolem](https://github.com/user-attachments/assets/f6121985-7f4d-4987-99a6-64e5dd3124c1)

**Comment by Egorundel** [comment]
@c7-biu What do you have at the input and output of the model?

**Comment by c7-biu** [comment]
Is this it?
![1](https://github.com/user-attachments/assets/7bd6d1d9-7dcc-4fe2-963b-34b1bdbed7fa)
I'm a novice at YOLO, so maybe I don't understand some of the technical words very well.

**Comment by c7-biu** [comment]
Is this it?
![Uploading 1.png…]()

I'm a novice at YOLO, so maybe I don't understand some of the technical words very well.
