### ISSUE TITLE
yolov4 to onnx error

### ISSUE THREAD

**Issue by Jeremy-J-J** [linghu8812/tensorrt_inference#2]
发生异常: ValidationError
Node (119_upsample) has input size 2 not in range [min=3, max=4].

==> Context: Bad node spec: input: "118_convolutional_lrelu" input: "119_upsample_scale" output: "119_upsample" name: "119_upsample" op_type: "Resize" attribute { name: "mode" s: "nearest" type: STRING }
  File "/home/7_pro/ToOnnx/tensorrt_inference/Yolov4/export_onnx.py", line 1090, in main
    onnx.checker.check_model(yolo_model_def)
  File "/home/7_pro/ToOnnx/tensorrt_inference/Yolov4/export_onnx.py", line 1108, in <module>
    neck=args.neck, sigmoid=args.sigmoid)

**Comment by linghu8812** [comment]
@Jeremy-J-J Hello，please use onnx==1.5.0.

**Comment by linghu8812** [comment]
I have add export onnx model with opset 10 code, onnx version has been no longer a restriction.
