### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hudfdfdf** [linghu8812/tensorrt_inference#20]
/tensorrt_inference/Yolov4/Yolov4.cpp: In member function ‘void YOLOv4::EngineInference(const std::vector<std::__cxx11::basic_string<char> >&, const int&, void**, const std::vector<long int>&, cudaStream_t)’:
tensorrt_inference/Yolov4/Yolov4.cpp:119:37: error: ‘std::chrono’ has not been declared
             auto t_start_pre = std::chrono::high_resolution_clock::now();
                                     ^
/tensorrt_inference/Yolov4/Yolov4.cpp:122:35: error: ‘std::chrono’ has not been declared
             auto t_end_pre = std::chrono::high_resolution_clock::now();
                                   ^
/tensorrt_inference/Yolov4/Yolov4.cpp:123:36: error: ‘std::chrono’ has not been declared
             float total_pre = std::chrono::duration<float, std::milli>(t_end_pre - t_start_pre).count();
                                    ^
/tensorrt_inference/Yolov4/Yolov4.cpp:123:53: error: expected primary-expression before ‘float’
             float total_pre = std::chrono::duration<float, std::milli>(t_end_pre - t_start_pre).count();
                                                     ^
/tensorrt_inference/Yolov4/Yolov4.cpp:137:33: error: ‘std::chrono’ has not been declared
             auto t_start = std::chrono::high_resolution_clock::now();
                                 ^
/tensorrt_inference/Yolov4/Yolov4.cpp:139:31: error: ‘std::chrono’ has not been declared
             auto t_end = std::chrono::high_resolution_clock::now();
                               ^
/tensorrt_inference/Yolov4/Yolov4.cpp:140:36: error: ‘std::chrono’ has not been declared
             float total_inf = std::chrono::duration<float, std::milli>(t_end - t_start).count();
                                    ^
/tensorrt_inference/Yolov4/Yolov4.cpp:140:53: error: expected primary-expression before ‘float’
             float total_inf = std::chrono::duration<float, std::milli>(t_end - t_start).count();
                                                     ^
/tensorrt_inference/Yolov4/Yolov4.cpp:146:33: error: ‘std::chrono’ has not been declared
             auto r_start = std::chrono::high_resolution_clock::now();
                                 ^
/tensorrt_inference/Yolov4/Yolov4.cpp:151:31: error: ‘std::chrono’ has not been declared
             auto r_end = std::chrono::high_resolution_clock::now();
                               ^
/tensorrt_inference/Yolov4/Yolov4.cpp:152:36: error: ‘std::chrono’ has not been declared
             float total_res = std::chrono::duration<float, std::milli>(r_end - r_start).count();
                                    ^
/Yolov4/Yolov4.cpp:152:53: error: expected primary-expression before ‘float’
             float total_res = std::chrono::duration<float, std::milli>(r_end - r_start).count();
                                                     ^
CMakeFiles/Yolov4_trt.dir/build.make:75: recipe for target 'CMakeFiles/Yolov4_trt.dir/Yolov4.cpp.o' failed
make[2]: *** [CMakeFiles/Yolov4_trt.dir/Yolov4.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Yolov4_trt.dir/all' failed
make[1]: *** [CMakeFiles/Yolov4_trt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for sharing the code, I encountered the above problem when compiling, can you give me some suggestions

**Comment by linghu8812** [comment]
#4
