### ISSUE TITLE
yolov4 trt的输入尺寸问题

### ISSUE THREAD

**Issue by DaChaoXc** [linghu8812/tensorrt_inference#31]
转onnx的时候需要指定w和h，比如640*640，如果指定w=640，h=360，在trt infer的时候输入也是640*360，是不是也可以得到正确的检测结果？毕竟pad之后的图像有效内容是一样的，只是pad的大小不一样而已，去卷积全黑或者灰色的paded区域其实没有意义，而输入是640*360感觉是间接的加速了。

**Comment by DaChaoXc** [comment]
![rsz_img](https://user-images.githubusercontent.com/14355882/106411428-46b83180-6480-11eb-8220-c1a0b814e7d5.jpg)
![rsz_pytorch](https://user-images.githubusercontent.com/14355882/106411441-4ae44f00-6480-11eb-95c9-c5d29c46b5a3.jpg)
 std::vector<cv::Mat> split_img = {
        // attention!!!cv::Mat init style: h w
        cv::Mat(IMAGE_HEIGHT, IMAGE_WIDTH, CV_32FC1,
                data + channelLength * (index + 2)),
        cv::Mat(IMAGE_HEIGHT, IMAGE_WIDTH, CV_32FC1,
                data + channelLength * (index + 1)),
        cv::Mat(IMAGE_HEIGHT, IMAGE_WIDTH, CV_32FC1,
                data + channelLength * index)};
修改这一处即可

**Comment by linghu8812** [comment]
solved https://github.com/linghu8812/tensorrt_inference/commit/4390224b2527ce56230522197ed80a7bfdc76b57
