### ISSUE TITLE
Build nanodet_trt project error

### ISSUE THREAD

**Issue by qiaoshh** [linghu8812/tensorrt_inference#38]
undefined reference to 'YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder>)'

**Comment by linghu8812** [comment]
Is the yaml version right? Try to link with [libyaml-cpp.a](https://github.com/linghu8812/tensorrt_inference/blob/master/includes/yaml-cpp/libs/libyaml-cpp.a)

**Comment by qiaoshh** [comment]
问题解决啦，YAML重新编译就好了，谢谢。
