### ISSUE TITLE
Do I need to destroy stream after every run?

### ISSUE THREAD

**Issue by xxxpsyduck** [linghu8812/tensorrt_inference#49]
I trying to do inference with video input. After running inference on a frame, do I need to destroy the stream and recreate a new one for new frame?

**Comment by linghu8812** [comment]
no need

**Comment by linghu8812** [comment]
Here is an TensorRT inference on video example which includes detection and tracking: [https://github.com/linghu8812/tensorrt_tracker](https://github.com/linghu8812/tensorrt_tracker)
