### ISSUE TITLE
Why workspace size set so low in common.hpp?

### ISSUE THREAD

**Issue by LukeAI** [linghu8812/tensorrt_inference#56]
In common.hpp `config->setMaxWorkspaceSize(16_MiB);`

This seems to be associated with the warning:

`Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.`

Why is maxworkspacesize set so low?

**Comment by linghu8812** [comment]
https://github.com/linghu8812/tensorrt_inference/blob/5f22509ead8c5b3432b682dde956d1cbcae0137c/includes/common/common.hpp#L132

please pull the latest code

**Comment by LukeAI** [comment]
thanks!

**Comment by abuelgasimsaadeldin** [comment]
Hi @linghu8812 I am using a Jetson Nano device and I am facing this error even with the latest pull ```config->setMaxWorkspaceSize(1_GiB); ``` then I receive the following error ````engine->getNbBindings() == 2' failed``` I have looked at the other issues and confirmed that my ONNX file is correct and produces the right output. Any advice?
