### ISSUE TITLE
[yolov5] Assertion `engine->getNbBindings() == 2' failed

### ISSUE THREAD

**Issue by hp2304** [linghu8812/tensorrt_inference#7]
While running "./yolov5_trt ../config.yaml ../samples" I encounterd,

_yolov5/yolov5.cpp:55: bool YOLOv5::InferenceFolder(const string&): Assertion `engine->getNbBindings() == 2' failed.
Aborted (core dumped)_

Engine file was successfully read from the file.

config.yaml:

onnx_file:     "../yolov5m.onnx"
engine_file:   "../yolov5m.trt"
labels_file:   "../coco.names"
BATCH_SIZE:    1
INPUT_CHANNEL: 3
IMAGE_WIDTH:   608
IMAGE_HEIGHT:  608
obj_threshold: 0.4
nms_threshold: 0.45
stride:        [8, 16, 32]
anchors:       [[10,13], [16,30], [33,23], [30,61], [62,45], [59,119], [116,90], [156,198], [373,326]]

yolov5m.onnx was generated using export_onnx.py as shown in the readme. Args were configured as above. **yolov5m.pt** model was downloaded from the latest release tag of ultralytics/yolov5 repo. What am I doing wrong?

**Comment by hp2304** [comment]
Sorry for creating this issue forgot to check the closed issue. Got the solution thanks works like a charm. Also, I wanted to do the same for my custom yolov5s model, should I follow this exact same procedure? And can you provide python code for doing inference instead of the current C++ code. Thanks again.

**Comment by linghu8812** [comment]
@hp2304 
1. yes, for custom yolov5 model, just follow the same procedure.
2. if you want to disable FP16 mode, try to comment this line:[https://github.com/linghu8812/tensorrt_inference/blob/ae17a94b727be8eccb8d0af9cdcb111d1f39a509/includes/common/common.hpp#L133](https://github.com/linghu8812/tensorrt_inference/blob/ae17a94b727be8eccb8d0af9cdcb111d1f39a509/includes/common/common.hpp#L133)
3. I am afraid that I do not have enough time to develop TensorRT inference code based on python recently.

**Comment by hp2304** [comment]
@linghu8812 Thanks for your reply. I will convert C++ code to python with the help of _tensorrtx_ repo listed on ultralytics/yolov5 repo.

**Comment by chandu1263** [comment]
@hp2304 were you able to convert this to python? If so, can you share the location please.
TIA

**Comment by AderonHuang** [comment]
> While running "./yolov5_trt ../config.yaml ../samples" I encounterd,
> 
> _yolov5/yolov5.cpp:55: bool YOLOv5::InferenceFolder(const string&): Assertion `engine->getNbBindings() == 2' failed. Aborted (core dumped)_
> 
> Engine file was successfully read from the file.
> 
> config.yaml:
> 
> onnx_file: "../yolov5m.onnx"
> engine_file: "../yolov5m.trt"
> labels_file: "../coco.names"
> BATCH_SIZE: 1
> INPUT_CHANNEL: 3
> IMAGE_WIDTH: 608
> IMAGE_HEIGHT: 608
> obj_threshold: 0.4
> nms_threshold: 0.45
> stride: [8, 16, 32]
> anchors: [[10,13], [16,30], [33,23], [30,61], [62,45], [59,119], [116,90], [156,198], [373,326]]
> 
> yolov5m.onnx was generated using export_onnx.py as shown in the readme. Args were configured as above. **yolov5m.pt** model was downloaded from the latest release tag of ultralytics/yolov5 repo. What am I doing wrong?

我遇到了同样的问题，请问你解决了吗？

**Comment by linghu8812** [comment]
same with #3 
使用https://github.com/linghu8812/yolov5 导出onnx模型

**Comment by AderonHuang** [comment]
你的模型用的是scale-yolov5吗？



---Original---

**Comment by AderonHuang** [comment]
> same with #3
> 使用https://github.com/linghu8812/yolov5 导出onnx模型

我用的就是这个导出的onnx模型，但是输出还是是5，能解答下吗

**Comment by linghu8812** [comment]
check these lines
https://github.com/linghu8812/yolov5/blob/11f7645e903377762622808aaa32d2369d89fc12/models/yolo.py#L42-L57
```
        # self.training |= self.export
        for i in range(self.nl):
            x[i] = self.m[i](x[i])  # conv
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            if not self.training:  # inference
                if not self.export:
                    if self.grid[i].shape[2:4] != x[i].shape[2:4]:
                        self.grid[i] = self._make_grid(nx, ny).to(x[i].device)

                y = x[i].sigmoid()
                if not self.export:
                    y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
                    y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
                z.append(y.view(bs, -1, self.no))
```

**Comment by AderonHuang** [comment]
> check these lines
> https://github.com/linghu8812/yolov5/blob/11f7645e903377762622808aaa32d2369d89fc12/models/yolo.py#L42-L57
> 
> ```
>         # self.training |= self.export
>         for i in range(self.nl):
>             x[i] = self.m[i](x[i])  # conv
>             bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
>             x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
> 
>             if not self.training:  # inference
>                 if not self.export:
>                     if self.grid[i].shape[2:4] != x[i].shape[2:4]:
>                         self.grid[i] = self._make_grid(nx, ny).to(x[i].device)
> 
>                 y = x[i].sigmoid()
>                 if not self.export:
>                     y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
>                     y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
>                 z.append(y.view(bs, -1, self.no))
> ```

yeah, I found this problem,now it is run correctly,but it is some problems happened,it stopped here is right??it so long
是的，我发现并解决了这个问题，但是现在卡在后处理，时间有几分钟了，这个正常吗
![image](https://user-images.githubusercontent.com/43173636/106106955-43236280-6181-11eb-8121-af2eaf8bd0cb.png)

**Comment by linghu8812** [comment]
ScaleYOLOv4的后处理需要优化

**Comment by AderonHuang** [comment]
https://github.com/linghu8812/tensorrt_inference/tree/master/ScaledYOLOv4
我用的是你提供的这个后处理呀，你那边单张图片前处理+inference+后处理需要多长时间呢

**Comment by AderonHuang** [comment]
> ScaleYOLOv4的后处理需要优化

https://github.com/linghu8812/tensorrt_inference/tree/master/ScaledYOLOv4
我用的是你提供的这个后处理呀，你那边单张图片前处理+inference+后处理需要多长时间呢

**Comment by AderonHuang** [comment]
> ScaleYOLOv4的后处理需要优化

一直卡在后处理这，是模型有问题吗

**Comment by AderonHuang** [comment]
> > ScaleYOLOv4的后处理需要优化
> 
> 一直卡在后处理这，是模型有问题吗

麻烦方便的时候解答下

**Comment by AderonHuang** [comment]
> > ScaleYOLOv4的后处理需要优化
> 
> https://github.com/linghu8812/tensorrt_inference/tree/master/ScaledYOLOv4
> 我用的是你提供的这个后处理呀，你那边单张图片前处理+inference+后处理需要多长时间呢

![image](https://user-images.githubusercontent.com/43173636/106113543-93062780-6189-11eb-86aa-48fe63a81361.png)

**Comment by linghu8812** [comment]
#26 
#33

**Comment by AderonHuang** [comment]
> #26
> #33 

感谢！我现在的问题应该后处理无法输出，时而报上面后处理报错或者直接卡在后处理，我现在用的是tensorrt7.2.1.6,转onnx的时候设置的opset_version=12，请问之前有遇到过这个问题吗

**Comment by upcdz** [comment]
> > same with #3
> > 使用https://github.com/linghu8812/yolov5 导出onnx模型
> 
> 我用的就是这个导出的onnx模型，但是输出还是是5，能解答下吗

你好，我的输出还是5，这个需要修改哪一部分啊？

**Comment by upcdz** [comment]
> check these lines
> https://github.com/linghu8812/yolov5/blob/11f7645e903377762622808aaa32d2369d89fc12/models/yolo.py#L42-L57
> 
> ```
>         # self.training |= self.export
>         for i in range(self.nl):
>             x[i] = self.m[i](x[i])  # conv
>             bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
>             x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
> 
>             if not self.training:  # inference
>                 if not self.export:
>                     if self.grid[i].shape[2:4] != x[i].shape[2:4]:
>                         self.grid[i] = self._make_grid(nx, ny).to(x[i].device)
> 
>                 y = x[i].sigmoid()
>                 if not self.export:
>                     y[..., 0:2] = (y[..., 0:2] * 2. - 0.5 + self.grid[i].to(x[i].device)) * self.stride[i]  # xy
>                     y[..., 2:4] = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i]  # wh
>                 z.append(y.view(bs, -1, self.no))
> ```

您好，这个地方需要修改哪些内容啊，我也是用这个转完onnx，输出还是5.
