### ISSUE TITLE
[yolov5] why do you modify yolo.py when export onnx?

### ISSUE THREAD

**Issue by clover978** [linghu8812/tensorrt_inference#82]
I notice that your forked repo [https://github.com/linghu8812/yolov5](https://github.com/linghu8812/yolov5) modified **yolo.py** when export onnx. 
https://github.com/linghu8812/yolov5/commit/9c2efc99df15359a408b228ebe675f98ba059555

I wonder what's the reason to those modifcations. Why don't you use the official version onnx?

Thanks a lot.

**Comment by linghu8812** [comment]
it makes convenience for post process to calculate bounding box

**Comment by PowerDi** [comment]
> it makes convenience for post process to calculate bounding box

Does it mean that I should use your 'yolo.py' in order to make onnx exporting normally?
