### ISSUE TITLE
p7 weights linkage is wrong, linked to yolov4-p6.pt

### ISSUE THREAD

**Issue by arnoldfychen** [linghu8812/tensorrt_inference#9]
Hello, 

Here in Model Zoo, 

yolov4-p7  [weights]([https://drive.google.com/file/d/1aB7May8oPYzBqbgwYSZHuATPXyxh9xnf/view?usp=sharing])  links to  yolov4-p6.pt , not yolov4-p7.pt

**Comment by linghu8812** [comment]
The link has been updated.

**Comment by arnoldfychen** [comment]
thanks for your quick update
