### ISSUE TITLE
Error while building make -j

### ISSUE THREAD

**Issue by MsWik** [linghu8812/tensorrt_inference#98]
**When building, I get the following error  **
**jetson NX **

[ 33%] Building CXX object CMakeFiles/ScaledYOLOv4_trt.dir/main.cpp.o
[ 66%] Building CXX object CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o
[100%] Linking CXX executable ScaledYOLOv4_trt
/usr/bin/ld: skipping incompatible /home/andry/tensorrt/tensorrt_inference/ScaledYOLOv4/../includes/yaml-cpp/libs/libyaml-cpp.a when searching for -lyaml-cpp
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::BadConversion::BadConversion(YAML::Mark const&)':
ScaledYOLOv4.cpp:(.text._ZN4YAML13BadConversionC2ERKNS_4MarkE[_ZN4YAML13BadConversionC5ERKNS_4MarkE]+0x6c): undefined reference to `vtable for YAML::BadConversion'
ScaledYOLOv4.cpp:(.text._ZN4YAML13BadConversionC2ERKNS_4MarkE[_ZN4YAML13BadConversionC5ERKNS_4MarkE]+0x70): undefined reference to `vtable for YAML::BadConversion'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::Node::Scalar[abi:cxx11]() const':
ScaledYOLOv4.cpp:(.text._ZNK4YAML4Node6ScalarB5cxx11Ev[_ZNK4YAML4Node6ScalarB5cxx11Ev]+0xb0): undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::TypedBadConversion<int>::~TypedBadConversion()':
ScaledYOLOv4.cpp:(.text._ZN4YAML18TypedBadConversionIiED2Ev[_ZN4YAML18TypedBadConversionIiED5Ev]+0x20): undefined reference to `YAML::BadConversion::~BadConversion()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::TypedBadConversion<float>::~TypedBadConversion()':
ScaledYOLOv4.cpp:(.text._ZN4YAML18TypedBadConversionIfED2Ev[_ZN4YAML18TypedBadConversionIfED5Ev]+0x20): undefined reference to `YAML::BadConversion::~BadConversion()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::TypedBadConversion<std::vector<int, std::allocator<int> > >::~TypedBadConversion()':
ScaledYOLOv4.cpp:(.text._ZN4YAML18TypedBadConversionISt6vectorIiSaIiEEED2Ev[_ZN4YAML18TypedBadConversionISt6vectorIiSaIiEEED5Ev]+0x20): undefined reference to `YAML::BadConversion::~BadConversion()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::TypedBadConversion<std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > >::~TypedBadConversion()':
ScaledYOLOv4.cpp:(.text._ZN4YAML18TypedBadConversionISt6vectorIS1_IiSaIiEESaIS3_EEED2Ev[_ZN4YAML18TypedBadConversionISt6vectorIS1_IiSaIiEESaIS3_EEED5Ev]+0x20): undefined reference to `YAML::BadConversion::~BadConversion()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::detail::node& YAML::detail::node_data::get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<YAML::detail::memory_holder>)':
ScaledYOLOv4.cpp:(.text._ZN4YAML6detail9node_data3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS0_4nodeERKT_St10shared_ptrINS0_13memory_holderEE[_ZN4YAML6detail9node_data3getINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS0_4nodeERKT_St10shared_ptrINS0_13memory_holderEE]+0xcc): undefined reference to `YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder>)'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o: In function `YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~TypedBadConversion()':
ScaledYOLOv4.cpp:(.text._ZN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED2Ev[_ZN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED5Ev]+0x20): undefined reference to `YAML::BadConversion::~BadConversion()'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o:(.data.rel.ro._ZTIN4YAML18TypedBadConversionISt6vectorIS1_IiSaIiEESaIS3_EEEE[_ZTIN4YAML18TypedBadConversionISt6vectorIS1_IiSaIiEESaIS3_EEEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o:(.data.rel.ro._ZTIN4YAML18TypedBadConversionISt6vectorIiSaIiEEEE[_ZTIN4YAML18TypedBadConversionISt6vectorIiSaIiEEEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o:(.data.rel.ro._ZTIN4YAML18TypedBadConversionIfEE[_ZTIN4YAML18TypedBadConversionIfEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o:(.data.rel.ro._ZTIN4YAML18TypedBadConversionIiEE[_ZTIN4YAML18TypedBadConversionIiEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
CMakeFiles/ScaledYOLOv4_trt.dir/ScaledYOLOv4.cpp.o:(.data.rel.ro._ZTIN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for YAML::BadConversion'
collect2: error: ld returned 1 exit status
CMakeFiles/ScaledYOLOv4_trt.dir/build.make:182: recipe for target 'ScaledYOLOv4_trt' failed
make[2]: *** [ScaledYOLOv4_trt] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/ScaledYOLOv4_trt.dir/all' failed
make[1]: *** [CMakeFiles/ScaledYOLOv4_trt.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wgd4510** [comment]
Have you solved the problem

**Comment by romil611** [comment]
I'm facing same issue. Were you able to solve it?
